### ISSUE TITLE
Tag Bugzilla issues automatically with "pull" and add a link to the PR

### ISSUE THREAD

**Issue by wilzbach** [dlang/dlang-bot#135]
People tend to forgot this, e.g. https://github.com/dlang/phobos/pull/5594

Details
- The bot currently doesn't have write access to Bugzilla, but it shouldn't be hard to change this
- This should happen for `open` and `synchronize`
- The bot of course needs to query whether he has mentioned the PR on bugzilla before
- They keywords can be fetched directly in `getDescriptions` -> https://issues.dlang.org/buglist.cgi?bug_id=16993&ctype=csv&columnlist=short_desc,bug_status,resolution,bug_severity,priority,keywords

**Comment by jondegenhardt** [comment]
+1   Was visiting to file this enhancement request (after seeing  [dlang/phobos#5593](https://github.com/dlang/phobos/pull/5593)).   If the bot tagged the bugzilla ticket at the time the PR is opened, the person would filed the ticket and any other interested parties would be notified of a PR they are interested in, potentially in time to help with a review. :)

**Comment by wilzbach** [comment]
>  If the bot tagged the bugzilla ticket at the time the PR is opened,

Unfortunately many people have troubles referencing the Bugzilla issue and need to rebase at least once ..

**Comment by wilzbach** [comment]
@braddr is there any catch to get bzAPI or an upgrade to Bugzilla 5 which if I understand it correctly has a REST endpoint included?
This would be a great help in introducing more automation to Bugzilla and also allow other use cases (like for example using Bugzilla conveniently on the phone)

**Comment by MartinNowak** [comment]
> Unfortunately many people have troubles referencing the Bugzilla issue and need to rebase at least once

But eventually everyone succeeds so we maintain our changelog. I think this is a fabulous idea. While more activity happens on GH, Bugzilla knows the stakeholders that could help with reviewing.

**Comment by wilzbach** [comment]
With https://github.com/dlang/dlang-bot/pull/225 now notifications are automatically triggered. So I guess we can close this?

**Comment by ZombineDev** [comment]
The bot tags the issues with the `pull` keyword (see e.g. https://issues.dlang.org/show_activity.cgi?id=19686), so I think we can finally close this.
