### ISSUE TITLE
Re-enable Travis build auto-cancelling

### ISSUE THREAD

**Issue by wilzbach** [dlang/dlang-bot#143]
On force-pushes previous builds aren't cancelled:

![image](https://user-images.githubusercontent.com/4370550/28252562-a5e553a6-6a95-11e7-880a-75f68ae58812.png)

So imho we should re-enable our working Travis PR canceller for dmd and possibly vibe.d.

If you look at the [build history](https://travis-ci.org/dlang/dmd/pull_requests), I manually cancelled these builds.

See also: https://github.com/dlang-bots/dlang-bot/pull/75

**Comment by MartinNowak** [comment]
Was already wondering what was going on.

**Comment by CyberShadow** [comment]
We don't use Travis any more, do we? Should this be closed?
