### ISSUE TITLE
Handle changes from enhancement to fix (or the opposite)

### ISSUE THREAD

**Issue by Basile-z** [dlang/dlang-bot#192]
Otherwise two contradictory labels can sit together, like here https://github.com/dlang/phobos/pull/6302.
Although i understand it might be complicated if the bot is only plugged to GH.

**Comment by wilzbach** [comment]
Wouldn't be so difficult, we would just need to check for the existence of any non-applied bugzilla label e.g. here:

https://github.com/dlang-bots/dlang-bot/blob/1051262d3d8cabcf26611444abcf0eb90d65a52f/source/dlangbot/app.d#L238-L242

and then remove them accordingly.
