### ISSUE TITLE
Smart WIP handling

### ISSUE THREAD

**Issue by BBasile** [dlang/dlang-bot#222]
Maybe handling of the `automerge` kinds of labels should be shortcut by the presence of a `WIP` label ?

**Comment by BBasile** [comment]
A bit like https://docs.gitlab.com/ee/user/project/merge_requests/work_in_progress_merge_requests.html

**Comment by BBasile** [comment]
well assuming WIP is not a standard

**Comment by wilzbach** [comment]
FWIW this one is more critical: https://github.com/dlang/dlang-bot/issues/191
