### ISSUE TITLE
Detect weblinks as reference to bugtracker issue

### ISSUE THREAD

**Issue by JohanEngelen** [dlang/dlang-bot#260]
Please expand the regex to recognize whether a commit message contains a reference to an issue, by detecting weblinks too. For example a commit message like this: "Fixes https://issues.dlang.org/show_bug.cgi?id=21202"

Thanks!

**Comment by MoonlightSentinel** [comment]
That is a horrible commit title because it doesn't contain any information about the actual changes (without visiting the bug tracker).

Compare
```
...
Fixes https://issues.dlang.org/show_bug.cgi?id=21202
...
```
to
```
...
Fix 21202:  std.algorithm.mutation.moveEmplace cannot deduce purity and errors
...
```
So I don't think we should support it.

**Comment by JohanEngelen** [comment]
What you show, "Fix 21202: std.algorithm.mutation.moveEmplace cannot deduce purity and errors", also does not contain any information about the actual changes. The issue detection mechanism should not be meant to ensure that people write a good commit message.

**Comment by MoonlightSentinel** [comment]
> What you show, "Fix 21202: std.algorithm.mutation.moveEmplace cannot deduce purity and errors", also does not contain any information about the actual changes.

It describes the bug that was resolved with this commit, which is much more than just a URL.

> The issue detection mechanism should not be meant to ensure that people write a good commit message.

If the bot allows this form, it will be criticized during review, which in turn requires additional time from contributor and reviewer(s).

---

Whats the benefit of your proposed title?

**Comment by JohanEngelen** [comment]
> Whats the benefit of your proposed title?

I'm not proposing a title.

The benefit is that it allows the dev to put in a commit message that is a little more helpful than "fix 123", and less need to remember the idiosyncrasy of the tooling.

**Comment by wilzbach** [comment]
We'll switch soon to GitHub issues, so I am not sure whether it is a good idea to invest more time into the legacy bugzilla bridge.

**Comment by JohanEngelen** [comment]
> We'll switch soon to GitHub issues, so I am not sure whether it is a good idea to invest more time into the legacy bugzilla bridge.

Makes sense.
(with Github, we'll get automatically the more extended detection what I asked for too)
