### ISSUE TITLE
Heroku stack is deprecated

### ISSUE THREAD

**Issue by Geod24** [dlang/dlang-bot#264]
<img width="556" alt="Screen Shot 2020-12-29 at 14 40 15" src="https://user-images.githubusercontent.com/2180215/103261189-e39c3080-49e3-11eb-920e-e3f1c7151da6.png">

CC @wilzbach @PetarKirov

**Comment by CyberShadow** [comment]
We're moving away from Heroku, so this should not be an issue going forward.
