### ISSUE TITLE
dlang-bot for dub didn't tag the latest release

### ISSUE THREAD

**Issue by Geod24** [dlang/dlang-bot#266]
Currently there is only a tag:
<img width="1250" alt="Screen Shot 2021-01-09 at 16 00 40" src="https://user-images.githubusercontent.com/2180215/104085558-df013300-5293-11eb-949c-9097b5fe625a.png">

We also had an issue with the latest release not having builds for everything: https://github.com/dlang/dub/issues/2038

**Comment by CyberShadow** [comment]
The logs on Heroku only go back a very short amount of time, so if I understand correctly, we don't have a way to retroactively check what happened there.

Please ping/reopen if it happens again (after the migration away from Heroku completes)?
