### ISSUE TITLE
Bot didn't catch second bugfix

### ISSUE THREAD

**Issue by berni44** [dlang/dlang-bot#268]
See [Phobos PR](https://github.com/dlang/phobos/pull/7793).

**Comment by Geod24** [comment]
The commit message doesn't include any reference to it, it is only present in the PR title.
I recommend "Fix 21635, 21636:" for this, as the "issue" is optional nowadays to allow for shorter commit messages.

**Comment by berni44** [comment]
> The commit message doesn't include any reference to it, it is only present in the PR title.

It does. The full commit message is:

```
Fix issue 21635 - std.bitmanip: bitfields should produce better error messages with wrong parameters
Fix issue 21636 - std.bitmanip: bitfields size of bitfield should be checked against size of used type
```
