### ISSUE TITLE
Tweaking bot with draft might be possible

### ISSUE THREAD

**Issue by berni44** [dlang/dlang-bot#270]
I'm not sure about this, I didn't try (as this feels unethically), but I suspect, that the following is possible to add unreviewed code:

- File a PR and wait for `automerge` label being added, while testers are still running.
- Convert to draft.
- Add new commits with the "unreviewed code".
- Convert back.

Maybe I'm wrong, but I think, the bot will never remove the `automerge` label during this process and thus will eventually merge everything.

IMHO, when converting to draft, the label should be removed.

**Comment by CyberShadow** [comment]
Since it's not possible to merge draft PRs from the web, I would imagine that the API call to do so would similarly fail.

I think we should close this unless evidence comes up that we need to take action.
