### ISSUE TITLE
Spurious escape in bug description 

### ISSUE THREAD

**Issue by MoonlightSentinel** [dlang/dlang-bot#276]
dlang-bot added an extra `\` to the description of [this issue](https://issues.dlang.org/show_bug.cgi?id=21951) in   dlang/dmd#12586.

Description from the bot message:
```
Segfault on noreturn\.init
```

Bugzilla title:
```
Segfault on noreturn.init
```

**Comment by CyberShadow** [comment]
It attempted to escape the \` by doubling it:
https://github.com/CyberShadow/dlang-bot/blob/21336e502f97e582a6cb4deab5d232c476060c5f/source/dlangbot/github.d#L42

That didn't work. I don't know why it tried to do it that way.
