### ISSUE TITLE
Post a comment when auto-merge is toggled on

### ISSUE THREAD

**Issue by wilzbach** [dlang/dlang-bot#32]
> I prefer the auto-merge system actually posting the message that auto merge has been toggled on, because that goes to my inbox.

reported by @schveiguy

**Comment by schveiguy** [comment]
Also should post when it's toggled off as well, for completeness!

**Comment by MartinNowak** [comment]
Please not more comments, github already shows label added and label removed info, without sending lots of mails.

**Comment by schveiguy** [comment]
Except I don't get notifications for the labels. All I will see is "dlang bot merged". Can we get a comment from the bot when merging on whose behalf? The merge commit doesn't get sent out in email either

**Comment by MartinNowak** [comment]
You do get GH notifications for merges (and those can be mailed), should be enough.

**Comment by schveiguy** [comment]
FYI: https://github.com/dlang/druntime/pull/1743#issuecomment-287421181

**Comment by MartinNowak** [comment]
I'm not using mail in my GH workflow, so I might miss the point, but I'm very opposed to add even more noise.

**Comment by schveiguy** [comment]
I'm not sure it's relevant to me anymore. I have learned to ignore the commit messages I see in my email, and look directly at the github discussion, and look for the labels before doing any reviews.

**Comment by CyberShadow** [comment]
Usually auto-merge is enabled along with approving the PR, and approving does generate an email today, so hopefully that should be sufficient.
