### ISSUE TITLE
auto-merge-autosquash

### ISSUE THREAD

**Issue by wilzbach** [dlang/dlang-bot#64]
Idea from @CyberShadow:

> Actually, would be cool if [DLang-Bot] could auto-squash `--fixup` commits.

**Comment by CyberShadow** [comment]
As I've feared, today I noticed the first attempted murder of my elaborate commit messages: 

https://github.com/dlang/druntime/pull/1784

Perhaps an improved solution would be:

- When auto-merging, *always* fixup commits that are made with `--squash` / `--fixup` (i.e. those whose commit messages begin with `squash! ` or `fixup! `, or those whose commit messages begin with `[SQUASH] ` as this seems to be a common practice
- Remove the `auto-merge-squash` label
- Instruct contributors to format fixup commits' messages in the above-described ways when creating them.

**Comment by MartinNowak** [comment]
Agreed that PRs merged in commits like
https://github.com/dlang/phobos/commit/d6d6831d3bbeaaf5e81c0f9634e3489a4f50d52b
aren't ideal and only leave information on GH, but no longer in the git history.
Overall I find all of this squashing business annoying, it hardly hurts anyone if a merged branch contains several commits. It's only a single merge commit after all.
OTOH github has this annoying visualization where they show all the individual commits, https://github.com/dlang/druntime/commits/master, but still what purpose does squashing serve?

**Comment by MartinNowak** [comment]
At the moment we're using GH's API to merge https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button, so it's not a simple option.

**Comment by MartinNowak** [comment]
I'll remove the auto-merge-squash labels until the commit message issues are properly resolved.

**Comment by wilzbach** [comment]
> I'll remove the auto-merge-squash labels until the commit message issues are properly resolved.

Looking at the current review queue for the DLang-Bot, this might take a while :/

FWIW isn't it easier to explain to @andralex that you don't want sensible commits to be squashed?

**Comment by MartinNowak** [comment]
Currently the bot only has a ref to the PR as merge message, thus all commit messages of the squashed PR are lost, until that get's fixed the feature is outright broken.

**Comment by wilzbach** [comment]
> Currently the bot only has a ref to the PR as merge message, thus all commit messages of the squashed PR are lost, until that get's fixed the feature is outright broken.

But that's intended! If you don't trust the contributors to use it properly, that's a big statement about the circle of trust... 
In any case we could do sth. like @CyberShadow and require fixup or squash in the commit messages to be part of at least one the commit message.

**Comment by MartinNowak** [comment]
> But that's intended! If you don't trust the contributors to use it properly, that's a big statement about the circle of trust...

It doesn't even preserve the first commit message!
Let's split of that bug ticket from the `--autosquash` enhancement though.

**Comment by MartinNowak** [comment]
see https://github.com/dlang-bots/dlang-bot/issues/66

**Comment by MartinNowak** [comment]
Only few people will use it, but I'm for teaching dlang-bot to understand `--autosquash` for auto-merge-squash, but defaulting to a single commit when no such prefixes are found.
Of course preserving the commit message (of any commit and any squash, but ditching fixups) is a requirement for both.

**Comment by CyberShadow** [comment]
> Actually, would be cool if [DLang-Bot] could auto-squash `--fixup` commits.

GitHub now shows diffs for force-pushes, so this feature suggestion is no longer useful. People should just force-push instead of pushing `--fixup` commits.
